### ISSUE TITLE
Wrong decoding of ofp_action_output.max_len

### ISSUE THREAD

**Issue by JanScheurich** [TrafficLab/of11softswitch#1]
The OF protocol decoder has a problem with the ofp_action_out{port=CONTROLLER,max_len=0x600} e.g. inside an ofp_flow_mod message. 

The symptom was that a sent max_len parameter was ignored and replaced by value 0.

I found the fault in file oflib/ofl-actions-unpack.c

```
 da = (struct ofl_action_output *)malloc(sizeof(struct ofl_action_output));
 da->port = ntohl(sa->port);
 da->max_len = ntohl(sa->max_len);      // FAULT
```

Since max_len is defined as uint16, you should use ntohs() instead.

**Comment by ZoltanLajosKis** [comment]
Fixed in comit:
https://github.com/TrafficLab/of11softswitch/commit/121c1cf24c967e98577eda506bd60062f1a80125
